# -*- coding: utf-8 -*-
"""final M4a to wav.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5BpWxe2wIJhxCIUMDTWrQiA0Nmycmf4

以下為M4a 轉 mp3
"""

!pip install pydub

from google.colab import files
from pydub import AudioSegment

# 上傳檔案
uploaded = files.upload()

# 定義轉換函式
def convert_m4a_to_mp3(input_file, output_file):
    sound = AudioSegment.from_file(input_file)
    sound.export(output_file, format="mp3")
    print(f"已將 {input_file} 轉換為 {output_file}")

# 將上傳的檔案儲存到Colab工作目錄中
for filename in uploaded.keys():
    input_file = filename
    output_file = f"{filename.split('.')[0]}.mp3"
    convert_m4a_to_mp3(input_file, output_file)

from google.colab import drive
drive.mount('/content/drive')

"""以下為 音檔轉成文字檔


"""

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

!whisper "/content/語音 146_sd (2).mp3" --language Chinese --model large-v3